# 運行模式 (debug:調試,test:測試,release:正式)
run_mode = "debug"

# swagger 配置
swagger = true

# 443 配置
https =false

# mysql 
[mysql]
host = "127.0.0.1"
port= 3306
user = "root"
password = "cqig7777"
db_name = "test"
parameters = "parseTime=true"
