# 運行模式 (debug:調試,test:測試,release:正式)
run_mode = "release"

# swagger 配置
swagger = true

# 443 配置
https = false

# Logger 配置
[Logconf]
logger = true
loggerToFile = true
loggerToDB = true

# mysql 
[mysql]
host = "34.92.36.107"
port= 32001
user = "root"
password = "cqig7777"
db_name = "zor"
parameters = "parseTime=true"

[mycard]
facServiceID = "zortest123"

[casino]
testip =  "34.92.237.98:30001"
proip =  "34.92.237.98:30001"