# 運行模式 (debug:調試,test:測試,release:正式)
run_mode = "test"

# swagger 配置
swagger = true

# 443 配置
https = false

# Logger 配置
logger = true

# mysql 
[mysql]
host = "34.92.36.107"
port= 32001
user = "root"
password = "cqig7777"
db_name = "zor"
parameters = "parseTime=true"
