# 運行模式 (debug:調試,test:測試,release:正式)
runMode = "debug"

# swagger 配置
swagger = true

# 443 配置
[http]
https = false
httpport = 8081

# Logger 配置
[Logconf]
logger = true
loggerToFile = true
loggerToDB = true

# mysql 
[mysql]
host = "34.92.36.107"
port= 32001
user = "root"
password = "cqig7777"
dbname = "zor"
parameters = "parseTime=true"
# host = ""
# port= 3306
# user = "cqig"
# password = "E1f1ee0cfcbb93EA"
# db_name = "marbles"
# parameters = "parseTime=true"

# Postgres 
[Postgres]
host = "192.168.2.25"
port= 5432
user = "postgres"
password = "123456"
dbName = "test"

[mycard]
facServiceID = "CQIG"

[casino]
betaip =  "35.194.245.46:30001"
proip =   "35.194.245.46:30001"
# proip =  "35.187.151.133:30001"