# 運行模式 (debug:調試很多很多的log,test:測試,release:正式)
runMode = "test"
# 運行環境 (alpha:調試,beta:測試,prod:正式)
runEnv = "beta"

# swagger 配置
swagger = true

# 443 配置
[http]
https = false
httpport = 8081

# Logger 配置
[Logconf]
logger = true
loggerToFile = true
loggerToDB = true

# mysql 
[mysql]
host = "34.92.36.107"
port= 32001
user = "root"
password = "cqig7777"
dbname = "zor"
parameters = "parseTime=true&loc=Local"

# Postgres 
[Postgres]
host = "192.168.2.25"
port= 5432
user = "postgres"
password = "123456"
dbName = "test"

[mycard]
facServiceID = "CQIG"

[casino]
# TODO 要切換環境
# proip =  "35.187.151.133:30001" // betaip =  "35.194.245.46:30001"  //   alphaip ="34.92.237.98:30001"
alphaip ="34.92.237.98:30001"
betaip = "35.194.245.46:30001"
prodip =  "35.187.151.133:30001"
