info:
  contact:
    email: zor@cqiserv.com
    name: CQI-SERVICES
    url: http://www.cqiserv.com/
  description: This is a sample API server .
  license: {}
  title: 金流SERVER API
  version: 2020.1.08.1.1.3.1.a
paths:
  /json_post:
    post:
      parameters:
      - description: Name 名稱
        in: query
        name: name
        required: true
        type: string
      - description: Message
        in: query
        name: message
        required: true
        type: string
      - description: Num
        in: query
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200","message":"","name":"","num":"","status":"SUCCESS"}'
          schema:
            type: string
      summary: JSONtestPost
  /list:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: cqikey
        in: formData
        name: cqikey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":"SUCCESS"}'
          schema:
            type: string
        "400":
          description: '{"status":"FAIL"}'
          schema:
            type: string
      summary: ListServer
      tags:
      - Admin
  /register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: cqikey
        in: formData
        name: cqikey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"name":"test","token":"123456","status":"SUCCESS"}'
          schema:
            type: string
        "400":
          description: '{"status":"FAIL"}'
          schema:
            type: string
      summary: RegisterServer
      tags:
      - Admin
swagger: "2.0"
