info:
  contact:
    email: zor@cqiserv.com
    name: CQI-SERVICES
    url: https://www.cqiserv.com/
  description: This is a sample API server .
  license: {}
  title: 金流SERVER API
  version: "2020.07"
paths:
  /admin/platform:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 平台名稱
        in: formData
        name: PlatformName
        required: true
        type: string
      - description: 平台帳號
        in: formData
        name: PlatformAccount
        required: true
        type: string
      - description: 平台密碼
        in: formData
        name: PlatformPassword
        required: true
        type: string
      - description: 聯絡信箱
        in: formData
        name: PlatformEmail
        type: string
      - description: 群組代號 - 預設為1
        in: formData
        name: PlatformGroupID
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"ecode":200,"msg":"ok","data":{"Account":"test123","Token":"7z7cxTyljnCXAyOLd/sOTw","TokenSecret":"wFwTezBIL0oElVXC","Time":"2020-08-06 15:53:36"}}'
          schema:
            type: string
        "411":
          description: '{"ecode":1001,"msg":"請求參數短少或錯誤","data":null}'
          schema:
            type: string
      summary: PlatformRegisterServer 新增平台帳號
      tags:
      - Admin
  /json_post:
    post:
      parameters:
      - description: Name 名稱
        in: query
        name: name
        required: true
        type: string
      - description: Message
        in: query
        name: message
        required: true
        type: string
      - description: Num
        in: query
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200","message":"","name":"","num":"","status":"SUCCESS"}'
          schema:
            type: string
      summary: JSONtestPost
      tags:
      - Test
  /mycard/CreateMycardOder:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 玩家帳號ID
        in: formData
        name: userid
        required: true
        type: string
      - description: 遊戲GroupID
        in: formData
        name: groupid
        required: true
        type: string
      - description: 商品代號
        in: formData
        name: itemid
        required: true
        type: string
      - description: 商品價格
        in: formData
        name: itemprice
        required: true
        type: string
      - description: 平台token代號
        in: formData
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"還沒寫好"}'
          schema:
            type: string
        "400":
          description: '{"status":"FAIL",    "msg": "錯誤訊息"}'
          schema:
            type: string
      summary: AuthMycard
      tags:
      - MyCard
swagger: "2.0"
