definitions:
  casinogrpc.CasinoItem:
    properties:
      itemName:
        type: string
      itemType:
        type: integer
      platform:
        type: string
      price:
        type: integer
      productID:
        type: string
    type: object
  controller.Resp:
    properties:
      data:
        type: object
      ecode:
        type: integer
      msg:
        type: string
    type: object
  db.Order:
    properties:
      callbackOriginalData:
        type: string
      callbackURL:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      orderClientID:
        type: string
      orderDate:
        type: string
      orderGameSubID:
        type: string
      orderItemID:
        type: string
      orderItemPrice:
        type: string
      orderOriginalData:
        type: string
      orderSubID:
        type: string
      paymentID:
        type: string
      paymentTypeID:
        type: integer
      platformID:
        type: integer
      receivedCallbackDate:
        type: string
      stageType:
        type: integer
      status:
        type: string
      updatedAt:
        type: string
    type: object
  db.Platform:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      platformAccount:
        type: string
      platformEmail:
        type: string
      platformGroupID:
        type: integer
      platformName:
        type: string
      platformPassword:
        type: string
      platformToken:
        type: string
      platformTokenSecret:
        type: string
      status:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact:
    email: zor@cqiserv.com
    name: CQI-SERVICES
    url: https://www.cqiserv.com/
  description: This is a sample API server .
  license: {}
  title: 金流SERVER API
  version: "2020.08"
paths:
  /admin/order/{OrderSubID}:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 交易單子單號
        in: path
        name: OrderSubID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Resp'
        "411":
          description: Error
          schema:
            $ref: '#/definitions/controller.Resp'
      summary: OrderGet 查詢交易單
      tags:
      - Admin-Order
  /admin/orders:
    get:
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Order'
            type: array
      summary: OrderGetAll 查詢ALL帳號
      tags:
      - Admin-Order
  /admin/platform:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 平台名稱
        in: formData
        name: PlatformName
        required: true
        type: string
      - description: 平台帳號
        in: formData
        name: PlatformAccount
        required: true
        type: string
      - description: 平台密碼
        in: formData
        name: PlatformPassword
        required: true
        type: string
      - description: 聯絡信箱
        in: formData
        name: PlatformEmail
        type: string
      - description: 群組代號 - 預設為1
        in: formData
        name: PlatformGroupID
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Resp'
        "411":
          description: Error
          schema:
            $ref: '#/definitions/controller.Resp'
      summary: PlatformRegisterServer 新增平台帳號
      tags:
      - Admin-Platform
  /admin/platform/{PlatformAccount}:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 平台帳號
        in: path
        name: PlatformAccount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Resp'
        "411":
          description: Error
          schema:
            $ref: '#/definitions/controller.Resp'
      summary: PlatformGet 查詢帳號
      tags:
      - Admin-Platform
  /admin/platform/status/{PlatformAccount}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 平台帳號
        in: path
        name: PlatformAccount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Resp'
        "411":
          description: Error
          schema:
            $ref: '#/definitions/controller.Resp'
      summary: PlatformStatusDisable 停用帳號
      tags:
      - Admin-Platform
    put:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 平台帳號
        in: path
        name: PlatformAccount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Resp'
        "411":
          description: Error
          schema:
            $ref: '#/definitions/controller.Resp'
      summary: PlatformStatusEnable 啟用帳號
      tags:
      - Admin-Platform
  /admin/platforms:
    get:
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Platform'
            type: array
      summary: PlatformGetAll 查詢ALL帳號
      tags:
      - Admin-Platform
  /casino/shop/:
    get:
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/casinogrpc.CasinoItem'
      summary: GetItem 查詢casino商品清單
      tags:
      - Casino
  /casino/user/{UserID}:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: CASINO角色帳號
        in: path
        name: UserID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Resp'
        "411":
          description: Error
          schema:
            $ref: '#/definitions/controller.Resp'
      summary: GetItem 查詢casino用戶
      tags:
      - Casino
  /mycardsandbox/order:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 玩家帳號ID
        in: formData
        name: OrderClientID
        required: true
        type: string
      - description: 商品代號
        in: formData
        name: OrderItemID
        required: true
        type: string
      - description: 商品價格
        in: formData
        name: OrderItemPrice
        required: true
        type: string
      - description: 平台token代號
        in: formData
        name: PlatformToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Resp'
        "411":
          description: Error
          schema:
            $ref: '#/definitions/controller.Resp'
      summary: 新增 mycard 交易單
      tags:
      - MyCard-SandBox
swagger: "2.0"
