info:
  contact:
    email: zor@cqiserv.com
    name: CQI-SERVICES
    url: https://www.cqiserv.com/
  description: This is a sample API server .
  license: {}
  title: 金流SERVER API
  version: 2020.1.08.1.1.3.1.a
paths:
  /admin/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: account
        in: formData
        name: account
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: '{"name":"zor","status":"success","time":"2020-07-20 17:25:55","token":"Hqlur4OpUJveSpdy6rm+iw","tokenSecret":"Qvx5CXbGiZ5u1JdF"}'
          schema:
            type: string
        "400":
          description: '{"status":"FAIL"}'
          schema:
            type: string
        "411":
          description: '{"status":"FAIL"}'
          schema:
            type: string
      summary: UserRegisterServer
      tags:
      - Admin
  /json_post:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: Message
        in: query
        name: message
        required: true
        type: string
      - description: Num
        in: query
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200","message":"","name":"","num":"","status":"SUCCESS"}'
          schema:
            type: string
      summary: JSONtestPost
  /list:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: cqikey
        in: formData
        name: cqikey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":"SUCCESS"}'
          schema:
            type: string
        "400":
          description: '{"status":"FAIL"}'
          schema:
            type: string
      summary: ListServer
      tags:
      - Admin
  /test/A:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: cqikey
        in: formData
        name: cqikey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"name":"test","token":"123456","status":"SUCCESS"}'
          schema:
            type: string
        "400":
          description: '{"status":"FAIL"}'
          schema:
            type: string
      summary: TestRegisterServer
      tags:
      - Test
swagger: "2.0"
